version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - gradle --version
  build:
    commands:
      - gradle build

artifacts:
  files:
    - appspec.yml
    - template.yml
    - scripts/*
    - target/ROOT.war
    - template-configuration.json
