version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Golusss123/ITP-sample-java-project/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  job-completed!!!!:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Job Completed!!!!!!

workflows:
  my-custom-workflow:
    jobs:
      - job-completed!!!!
